django_tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^plant/', include('plant.urls')),
]

plant/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'plant'

urlpatterns = [
    # /plant/
    url(r'^$', login_required(views.TypeListView.as_view()), name='index'),
    
    #Login Action
    url(r'^login/$', views.action_login, name='action_login'),

    #Logout Action
    url(r'^logout/$', views.action_logout, name='action_logout'),

    #Login Page
    url(r'^login_page/$', views.LoginPage.as_view(), name='login-page'),

    #Registering
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /plant/perennials/
    # Note for class based views make sure you use pk
    url(r'^(?P<slug>[a-z]+)/$', login_required(views.TypeDetailView.as_view()), name='detail'),

    # /plant/type/1-tacosß
    url(r'^(?P<type>[a-z]+)/(?P<pk>[0-9]+)-(?P<name>[a-z]+)/$', login_required(views.PlantDetailView.as_view()), name='plant'),

    #URL that allows us to delete types
    # /plant/<type>/delete
    url(r'^(?P<slug>[a-z]+)/delete/$', login_required(views.TypeDelete.as_view()), name='type-delete'),

    #URL that allows us to update types
    # /plant/<type>/update
    url(r'^(?P<slug>[a-z]+)/update/$', login_required(views.TypeUpdate.as_view()), name='type-update'),

    #URL that allows us to delete individual plants
    # /plant/type/1-tacos/delete
    url(r'^(?P<type>[a-z]+)/(?P<pk>[0-9]+)-(?P<name>[a-z]+)/delete/$', login_required(views.PlantDelete.as_view()), name='plant-delete'),

    #URL that allows us to update individual plants
    # /plant/type/1-tacos/update
    url(r'^(?P<type>[a-z]+)/(?P<pk>[0-9]+)-(?P<name>[a-z]+)/update/$', login_required(views.PlantUpdate.as_view()), name='plant-update'),

    #URL for type form
    url(r'^type/add/$', login_required(views.TypeCreate.as_view()), name='type-add'),

    #URL for plant form
    url(r'^plants/add/$', login_required(views.PlantCreate.as_view()), name='plant-add'),
]

plant/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse


# Create your models here.
class Type(models.Model):
    users = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    t_name = models.CharField(max_length=250)
    t_img = models.CharField(max_length=1000)
    t_description = models.CharField(max_length=1000)
    slug = models.SlugField(default='', blank=True)

    #Used to generate a slug when saving for first time
    def save(self, *args, **kwargs):
        super(Type, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.t_name)
            self.save()

    def __str__(self):
        return self.t_name

    def get_absolute_url(self):
        return reverse("plant:detail", kwargs = {'slug': str(self.slug)})

class Plant(models.Model):
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    p_name = models.CharField(max_length=200)
    p_img = models.CharField(max_length=200)
    p_description = models.CharField(max_length=1000)
    p_quantity = models.IntegerField()
    p_favorite = models.BooleanField(default=False)
    slug = models.SlugField(default='', blank=True)

    #Used to generate a slug when saving for the first time
    def save(self, *args, **kwargs):
        super(Plant, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.p_name)
            self.save()

    def __str__(self):
        return self.p_name

    def get_absolute_url(self):
        #Gacky solution to make the name of the type lower case
        return reverse("plant:plant", kwargs = {'type': str(self.type).lower(), 'pk': str(self.id), 'name': str(self.slug)})

    def get_delete_url(self):
        return reverse("plant:plant-delete", kwargs = {'type': str(self.type).lower(), 'pk': str(self.id), 'name': str(self.slug)})

    def get_update_url(self):
        return reverse("plant:plant-update", kwargs = {'type': str(self.type).lower(), 'pk': str(self.id), 'name': str(self.slug)})

plant/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    #Widget helps protect the password
    password = forms.CharField(widget=forms.PasswordInput)

    #Contains info about your class
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

plant/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
#login gives them session id so they don't have to authenticate every time
from django.contrib.auth import authenticate, login, logout
#Added to ensure each page requires you to login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from .models import Type, Plant
from .forms import UserForm
# Create your views here.

@method_decorator(login_required, name='dispatch')
class TypeListView(generic.ListView):
    #Name which will be used in your templates to retrieve objects
    context_object_name = 'all_types'
    #Name of your actual template
    template_name = 'plant/index.html'

    #Necessary to filter out types available to a user
    def get_queryset(self):
        return Type.objects.filter(users = self.request.user)

@method_decorator(login_required, name='dispatch')
class TypeDetailView(generic.DetailView):
    #Expects pk from url
    model = Type
    #Name of object template will use
    context_object_name = 'type'
    #Name of actual template
    template_name = 'plant/detail.html'

    def get_context_data(self, **kwargs):
        #Call the base implementation first to get a context
        context = super(TypeDetailView, self).get_context_data(**kwargs)
        #Add in list of plants using query
        context['plants'] = Type.objects.get(t_name=self.kwargs['slug']).plant_set.all()
        return context;

@method_decorator(login_required, name='dispatch')
class PlantDetailView(generic.DetailView):
    #Expects pk from url
    model = Plant
    #Name of object template will use
    context_object_name = 'plant'
    #Name of actual template
    template_name = 'plant/plant.html'

@method_decorator(login_required, name='dispatch')
class TypeCreate(CreateView):
    model = Type
    fields = ['t_name', 't_img', 't_description']
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.users = self.request.user
        return super(TypeCreate, self).form_valid(form)

@method_decorator(login_required, name='dispatch')
class TypeDelete(DeleteView):
    model = Type
    #redirects to details page when finished deleting
    success_url = reverse_lazy('plant:index')

@method_decorator(login_required, name='dispatch')
class TypeUpdate(UpdateView):
    model = Type
    fields = ['t_name', 't_img', 't_description']

#Automatically detects plant-form.html just make sure to set up url
#html file should follow <Model Name>_form.html format
@method_decorator(login_required, name='dispatch')
class PlantCreate(CreateView):
    model = Plant
    fields = ['type', 'p_name', 'p_img', 'p_description', 'p_quantity']

@method_decorator(login_required, name='dispatch')
class PlantDelete(DeleteView):
    model = Plant
    #This piece of code is necessary because it allows us to go back to details page of type
    #After deleting a plant
    #We grab the type to go back to from the url using self.kwargs
    #https://stackoverflow.com/questions/10631381/redirect-to-parent-after-deleting-an-object-with-deleteobject-generic-view
    def get_success_url(self, **kwargs):
        return reverse('plant:detail', kwargs={'slug':self.kwargs['type']})

@method_decorator(login_required, name='dispatch')
class PlantUpdate(UpdateView):
    model = Plant
    fields = ['type', 'p_name', 'p_img', 'p_description', 'p_quantity']

class UserFormView(View):
    form_class = UserForm
    #html file that form is gunna be included in
    template_name = 'plant/registration_form.html'

    #display blank form
    def get(self, request):
        #Use default user form defined above in the UserFormView class
        #No need to pass in context
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    #When user submits form process it
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            #Creates object from the form but it doesn't save it to db yet
            user = form.save(commit=False)

            # cleaned and normalized data (data that is formatted correctly)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            #Manner in which we change user passwords
            user.set_password(password)
            #Adds user to db
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('plant:index')
            return render(request, self.template_name, {'form': form})

#View for login page
class LoginPage(TemplateView):
    template_name = "plant/login.html"

#Login
def action_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('plant:index')
    return render(request, "plant/login.html")

def action_logout(request):
    logout(request)
    return redirect('plant:login-page')

plant/templates/plant/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Plants{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'plant/style.css' %}">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Plants</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'plant:index' %}">Home</a></li>
                    <li><a href="{% url 'plant:type-add' %}">Add Type</a></li>
                    <li><a href="{% url 'plant:plant-add' %}">Add Plant</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'plant:action_logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

plant/templates/plant/detail.html
{% extends 'plant/base.html' %}
{% block title %}Type Details{% endblock %}
{% block body %}
<div class="container">
    <h1>{{ type }}</h1>
    <ul>
        {% for plant in plants %}
        <!--<li><a href="{{ plant.slug }}">{{ plant.p_name }}</a></li>-->
            <li><a href="{{ plant.get_absolute_url }}">{{ plant.p_name }}</a></li>
        {% endfor %}
    </ul>
    <form action="{% url 'plant:type-delete' type.slug %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span>
        </button>
    </form>
    <form action="{% url 'plant:type-update' type.slug %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-pencil"></span>
        </button>
    </form>
</div>
{% endblock %}

plant/templates/plant/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-8">{{ field }}</div>
    </div>
{% endfor %}

plant/templates/plant/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-8">{{ field }}</div>
    </div>
{% endfor %}

plant/templates/plant/index.html
{% extends 'plant/base.html' %}
{% block body %}
<div class="container">
    {% if all_types %}
    <h1>Here are all the plant types</h1>
    <ul>
        {% for type in all_types%}
        <li><a href="{{ type.get_absolute_url }}">{{ type.t_name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <h3>There are no plants to display</h3>
    {% endif %}
</div>
{% endblock %}

plant/templates/plant/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Plants Login{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Loads the path to your static files -->
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'plant/style.css' %}">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">   
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <!--<div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div> -->
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="loginform" action="{% url 'plant:action_login' %}"  method="POST" class="form-horizontal" role="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username">                                        
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                    </div>
                                
                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="{% url 'plant:register' %}">
                                            Sign Up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     
                        </div>                     
                    </div>  
        </div>>
</body>
</html>

plant/templates/plant/plant-form.html
{% extends 'plant/base.html' %}
{% block title %}Add Plant Type{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% include 'plant/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

plant/templates/plant/plant.html
{% extends 'plant/base.html' %}
{% block title %}Plant Details{% endblock %}
{% block body %}
<div class="container">
    <h1>{{ plant }}</h1>
    <img src="{{ plant.p_img }}">
    <h3>Description:</h3>
    <p>{{ plant.p_description }}</p>
    <h3>Quantity:</h3>
    <p>{{ plant.p_quantity }}</p>

    <form action="{{ plant.get_delete_url }}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span>
        </button>
    </form>
    <form action="{{ plant.get_update_url }}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-pencil"></span>
        </button>
    </form>

</div>
{% endblock %}

plant/templates/plant/plant_form.html
{% extends 'plant/base.html' %}
{% block title %}Add Plant Type{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% include 'plant/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

plant/templates/plant/registration_form.html
{% extends 'plant/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container">
    <h3>Register for New Account</h3>
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% include 'plant/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

plant/templates/plant/type_form.html
{% extends 'plant/base.html' %}
{% block title %}Add Plant Type{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% include 'plant/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}